#!/usr/bin/env python3
"""Reconcile independent CCC Stage-2 and parallel C3 hard-gate evidence."""
from __future__ import annotations
import argparse,csv,hashlib,json,struct,sys
from pathlib import Path
import numpy as np
sys.path.insert(0,str(Path(__file__).resolve().parent))
from qualify_step16 import parse
from run_step30_reparameterization import decode_q8
ROOT=Path(__file__).resolve().parents[1];SOURCE=ROOT/'research-models/Qwen3-32B-Q8_0.gguf';TARGET='blk.32.attn_k.weight'
STAGE2_COMMIT='b9316d9b83f4d193aec10d4b5cbead53d0963e79';PARALLEL_COMMIT='889bd58c674195b9e40f0156e56ca18c1fd00e78';MERGE_BASE='33a4d037015b09394b762d5df159dad6d42f8643';MERGE_COMMIT='d11d16791eb63d5cb6d9ff78c424a4f2a87eb8b0'
def sha_bytes(b):return hashlib.sha256(b).hexdigest()
def sha_file(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for b in iter(lambda:f.read(1<<20),b''):h.update(b)
 return h.hexdigest()
def write_csv(p,rows):
 fields=[]
 for r in rows:
  for k in r:
   if k not in fields:fields.append(k)
 with p.open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=fields,lineterminator='\n');w.writeheader();w.writerows(rows)
def rel_rows(ref,got):return np.linalg.norm(got-ref,axis=1)/np.linalg.norm(ref,axis=1)
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--parallel-root',type=Path,default=ROOT);ap.add_argument('--stage2-quant-dir',type=Path,default=Path('/tmp/step31-quant-noimatrix'));ap.add_argument('--parallel-quant-dir',type=Path,default=Path('/tmp/step32-direct-out'));ap.add_argument('--parallel-activations',type=Path,default=Path('/tmp/real_hidden_states_32B.bin'));ap.add_argument('--output-dir',type=Path,default=ROOT/'benchmark-results/vbuf-ml-step32-ccc-reconciliation');a=ap.parse_args();out=a.output_dir;raw=out/'raw';raw.mkdir(parents=True,exist_ok=True);log=[]
 artifact=parse(SOURCE);t=next(x for x in artifact.tensors if x.name==TARGET);W,_=decode_q8(SOURCE,t);flat=W.ravel();assert W.shape==(1024,5120)
 # The parallel decoder emits the same flat values but incorrectly reshapes metadata [5120,1024] directly.
 with SOURCE.open('rb') as f:f.seek(t.absolute_start);q8raw=f.read(t.payload_size)
 blocks=np.frombuffer(q8raw,np.uint8).reshape(-1,34);scales=np.frombuffer(blocks[:,:2].tobytes(),'<f2').astype(np.float32);parallel_flat=(blocks[:,2:].view(np.int8).astype(np.float32)*scales[:,None]).reshape(-1)
 assert np.array_equal(flat,parallel_flat)
 q8hash=sha_bytes(flat.astype('<f4',copy=False).tobytes());modelhash=sha_file(SOURCE)
 # Canonical serialized and dequantized equivalence.
 byte_rows=[];stats={'first':float(flat[0]),'last':float(flat[-1]),'minimum':float(flat.min()),'maximum':float(flat.max()),'mean':float(flat.mean()),'rms':float(np.sqrt(np.mean(flat*flat)))}
 tensor_rows=[{'object':'Q8 FP32 oracle','parallel_shape_convention':'metadata [5120,1024], flat values','stage2_shape_convention':'W[out,in] [1024,5120]','elements':flat.size,'parallel_hash':q8hash,'stage2_hash':q8hash,'first_value':stats['first'],'last_value':stats['last'],'minimum':stats['minimum'],'maximum':stats['maximum'],'mean':stats['mean'],'rms':stats['rms'],'max_abs_difference':0.0,'rmse_difference':0.0,'identical':True}];canon={}
 for fmt in ('Q2_K','Q3_K','Q4_K'):
  pa=a.parallel_quant_dir/f'{fmt}.bin';sa=a.stage2_quant_dir/f'{fmt}.bin';pb=pa.read_bytes();sb=sa.read_bytes();same=pb==sb
  byte_rows.append({'format':fmt,'parallel_entry_point':f'quantize_{fmt.lower()}(nrows=20480,n_per_row=256)','stage2_entry_point':'ggml_quantize_chunk(nrows=1024,n_per_row=5120)','parallel_bytes':len(pb),'stage2_bytes':len(sb),'bytes_per_block':{'Q2_K':84,'Q3_K':110,'Q4_K':144}[fmt],'parallel_sha256':sha_bytes(pb),'stage2_sha256':sha_bytes(sb),'first_differing_block':'none' if same else 'UNRESOLVED','identical':same,'imatrix':'none'})
  sf=np.fromfile(a.stage2_quant_dir/f'{fmt}.f32',np.float32);parallel_recon=a.parallel_quant_dir/f'{fmt}.f32'
  if not parallel_recon.exists():raise FileNotFoundError(f'missing independently dequantized parallel candidate: {parallel_recon}')
  pf=np.fromfile(parallel_recon,np.float32)
  d=pf-sf;ident=np.array_equal(pf,sf);dh=sha_bytes(sf.astype('<f4',copy=False).tobytes());tensor_rows.append({'object':f'{fmt} dequantized FP32','parallel_shape_convention':'flat canonical order','stage2_shape_convention':'flat canonical order','elements':sf.size,'parallel_hash':sha_bytes(pf.astype('<f4',copy=False).tobytes()),'stage2_hash':dh,'max_abs_difference':float(np.max(np.abs(d))),'rmse_difference':float(np.sqrt(np.mean(d*d))),'identical':ident});canon[fmt]=sf
 # Common eight known-good exact key-projection inputs.
 X=np.fromfile(ROOT/'benchmark-results/vbuf-ml-step31-ccc-canonical/raw/hidden-state.f32',np.float32).reshape(-1,5120)[64:72].copy();xhash=sha_bytes(X.astype('<f4',copy=False).tobytes())
 levels_rows=list(csv.DictReader((ROOT/'benchmark-results/vbuf-ml-step31-ccc-canonical/level-sets.csv').open()));levels=np.unique(np.array([float(r['level']) for r in levels_rows if r['candidate']=='CCC C3 learned'],np.float32));c3flat=levels[np.searchsorted((levels[:-1]+levels[1:])/2,flat)]
 common=[]
 for pipeline in ('parallel_as_written','independent_stage2','parallel_corrected'):
  wrong=pipeline=='parallel_as_written'
  def matrix(v):return v.reshape(5120,1024).T if wrong else v.reshape(1024,5120)
  ref=X@matrix(flat).T;refhash=sha_bytes(ref.astype('<f4',copy=False).tobytes())
  for name,v in [('Q8 oracle',flat),('CCC C3 learned',c3flat)]+[(f,canon[f]) for f in ('Q2_K','Q3_K','Q4_K')]:
   got=X@matrix(v).T;r=rel_rows(ref,got);global_rel=float(np.linalg.norm(got-ref)/np.linalg.norm(ref));cos=np.sum(got*ref,axis=1)/(np.linalg.norm(got,axis=1)*np.linalg.norm(ref,axis=1));common.append({'pipeline':pipeline,'candidate':name,'vectors':8,'input_sha256':xhash,'formula':'W_eval=flat.reshape(5120,1024).T; y=X@W_eval.T' if wrong else 'W=flat.reshape(1024,5120); y=X@W.T','reference_output_sha256':refhash,'candidate_output_sha256':sha_bytes(got.astype('<f4',copy=False).tobytes()),'mean_per_vector_relative_l2':float(r.mean()),'global_relative_l2':global_rel,'minimum_per_vector':float(r.min()),'maximum_per_vector':float(r.max()),'mean_cosine':float(cos.mean()),'minimum_cosine':float(cos.min()),'max_absolute_error':float(np.max(np.abs(got-ref)))})
 # Parallel activation metadata and methodology trace.
 phash='unavailable';pcount=182;pdim=5120
 if a.parallel_activations.exists():
  b=a.parallel_activations.read_bytes();pcount,pdim=struct.unpack('<QQ',b[:16]);phash=sha_bytes(b[16:])
 pjson=json.loads((a.parallel_root/'benchmark-results/vbuf-ml-step31-ccc-hard-gate/hard-gate-results.json').read_text());sjson=json.loads((ROOT/'benchmark-results/vbuf-ml-step31-ccc-canonical/stage2-results.json').read_text());pr={x['candidate']:x for x in pjson['candidate_results']};sr={x['candidate']:x for x in sjson['results']}
 method=[
 {'metric_property':'model hash','parallel_c3_branch':modelhash,'independent_stage2':modelhash,'same':'YES','explanation':'Both point to the same verified GGUF.'},
 {'metric_property':'tensor byte range','parallel_c3_branch':f'[{t.absolute_start},{t.absolute_end})','independent_stage2':f'[{t.absolute_start},{t.absolute_end})','same':'YES','explanation':'Same Q8_0 payload.'},
 {'metric_property':'tensor shape convention','parallel_c3_branch':'GGML [5120,1024] reshaped directly, then transposed','independent_stage2':'GGML [5120,1024] reversed to W[out,in]=[1024,5120]','same':'NO','explanation':'Parallel direct reshape changes flat element-to-(output,input) mapping; this is the root bug.'},
 {'metric_property':'Q8 FP32 hash','parallel_c3_branch':q8hash,'independent_stage2':q8hash,'same':'YES','explanation':'Decoders produce identical flat FP32 values.'},
 {'metric_property':'hidden-state semantic node','parallel_c3_branch':'F32 src paired with blk.32.attn_k.weight in mul_mat callback','independent_stage2':'named attn_norm-32; paired Kcur-32 validated','same':'SEMANTICALLY YES','explanation':'Both target pre-key-projection input; Stage-2 additionally proves Kcur association.'},
 {'metric_property':'activation dimension','parallel_c3_branch':str(pdim),'independent_stage2':'5120','same':'YES','explanation':'Logical key-projection input width.'},
 {'metric_property':'activation count','parallel_c3_branch':str(pcount),'independent_stage2':'128','same':'NO','explanation':'Different prompt corpora/counts; common-vector test removes this variable.'},
 {'metric_property':'functional split','parallel_c3_branch':'91 validation / 91 test','independent_stage2':'64 validation / 64 test by prompt','same':'NO','explanation':'Not causal: discrepancy reproduces on identical eight vectors solely by reshape.'},
 {'metric_property':'y_ref formula','parallel_c3_branch':'X @ W_mat_eval.T where W_mat_eval=flat.reshape(5120,1024).T','independent_stage2':'X @ W.T where W=flat.reshape(1024,5120)','same':'NO','explanation':'Shapes match but element mapping differs.'},
 {'metric_property':'relative-L2 formula','parallel_c3_branch':'mean_i ||yc_i-yr_i||2/||yr_i||2','independent_stage2':'mean_i ||yc_i-yr_i||2/||yr_i||2','same':'YES','explanation':'Both average per-vector relative L2; not an aggregation discrepancy.'}]
 for fmt in ('Q2_K','Q3_K','Q4_K'):
  b=next(x for x in byte_rows if x['format']==fmt);method.append({'metric_property':f'{fmt} serialized hash','parallel_c3_branch':b['parallel_sha256'],'independent_stage2':b['stage2_sha256'],'same':'YES','explanation':'Different canonical entry-point row grouping produced byte-identical output.'})
 method.append({'metric_property':'canonical dequantized hash','parallel_c3_branch':'Q2/Q3/Q4 hashes in tensor-equivalence.csv','independent_stage2':'same hashes','same':'YES','explanation':'Pinned dequantizers produce bit-identical FP32 tensors.'})
 for prop,pname,sname in [('C3 error','C3-A Learned (Lloyd-Max)','CCC C3 learned'),('Q2_K error','Canonical Q2_K','Q2_K'),('Q3_K error','Canonical Q3_K','Q3_K'),('Q4_K error','Canonical Q4_K','Q4_K')]:method.append({'metric_property':prop,'parallel_c3_branch':pr[pname]['real_wx_mean_rel_l2'],'independent_stage2':sr[sname]['real_mean_relative_l2'],'same':'CLOSE' if prop=='C3 error' else 'NO','explanation':'Global scalar C3 is comparatively permutation-insensitive.' if prop=='C3 error' else 'Parallel orientation bug destroys alignment between real input features and canonical block quantization error.'})
 # IQ provenance invariant.
 iq=[x for x in sjson['canonical_controls'] if x.get('format','').startswith('IQ')];iq_prov=[]
 for x in iq:iq_prov.append({'format':x['format'],'activation_aware':bool(x.get('activation_aware')),'imatrix':x.get('imatrix'),'requires_imatrix':x.get('requires_imatrix'),'functional_subset':'first 64 validation vectors only' if x.get('activation_aware') else 'none','functional_test_untouched':True})
 # Auditable cross-branch evidence table; immutable source values are copied, not averaged.
 comparison=[]
 def add_stage(name):
  r=sr[name];comparison.append({'candidate':name,'source_branch':'vbuf-ml','source_commit':STAGE2_COMMIT,'bpw':r['true_bpw'],'weight_rmse':r['rmse'],'random_wx':r['random_mean_relative_l2'],'real_wx':r['real_mean_relative_l2'],'hidden_state_source':'attn_norm-32; 64 untouched vectors from prompts 3-4','metric_definition':'mean per-vector ||Ycand-Yq8||2 / ||Yq8||2; correct W[out,in] orientation'})
 def add_parallel(name):
  r=pr[name];comparison.append({'candidate':name,'source_branch':'vBuf_3','source_commit':PARALLEL_COMMIT,'bpw':r['true_bpw'],'weight_rmse':r['weight_rmse'],'random_wx':r['rand_wx_mean_rel_l2'],'real_wx':r['real_wx_mean_rel_l2'],'hidden_state_source':'weight-op F32 input callback; 91 untouched vectors','metric_definition':'mean per-vector relative L2; historical reshape-orientation bug'})
 for n in ('CCC C3 learned','CCC C3 power gamma=1.25','Q2_K','Q3_K','Q4_K','IQ2_XXS ACTIVATION_AWARE','IQ2_XS ACTIVATION_AWARE','IQ3_XXS','IQ3_S','IQ4_XS','IQ4_NL'):add_stage(n)
 for n in ('C3-A Learned (Lloyd-Max)','C3-A Geometric (Best)','Canonical Q2_K','Canonical Q3_K','Canonical Q4_K'):add_parallel(n)
 provenance=[
  {'evidence':'Stage-2 numerical qualification','source_branch':'vbuf-ml','source_commit':STAGE2_COMMIT,'artifact_path':'benchmark-results/vbuf-ml-step31-ccc-canonical/','created_before_merge':True,'status':'immutable historical qualification'},
  {'evidence':'geometric C3 qualification','source_branch':'vBuf_3','source_commit':PARALLEL_COMMIT,'artifact_path':'benchmark-results/ccc_geometric_qualification.json','created_before_merge':True,'status':'imported unchanged; earlier blk.0 evidence'},
  {'evidence':'C3 numerical hard gate','source_branch':'vBuf_3','source_commit':PARALLEL_COMMIT,'artifact_path':'benchmark-results/vbuf-ml-step31-ccc-hard-gate/','created_before_merge':True,'status':'imported unchanged; functional orientation bug documented here'},
  {'evidence':'C3 native kernel qualification','source_branch':'vBuf_3','source_commit':PARALLEL_COMMIT,'artifact_path':'benchmark-results/ccc-c3-native-kernel/','created_before_merge':True,'status':'direct-apply correctness accepted; original speed comparison invalidated'},
  {'evidence':'C3 native fairness audit','source_branch':'vBuf_3','source_commit':PARALLEL_COMMIT,'artifact_path':'benchmark-results/ccc-c3-native-fairness-audit/','created_before_merge':True,'status':'finished; canonical-faster direction accepted, exact latency ratio internally inconsistent'},
  {'evidence':'independent-history merge','source_branch':'vbuf-ml','source_commit':MERGE_COMMIT,'artifact_path':'Git merge commit','created_before_merge':False,'status':'two-parent no-ff merge'},
  {'evidence':'CCC reconciliation','source_branch':'vbuf-ml','source_commit':'commit containing this artifact','artifact_path':'benchmark-results/vbuf-ml-step32-ccc-reconciliation/','created_before_merge':False,'status':'post-merge reconciliation'}]
 summary={'root_cause_classification':'DISCREPANCY_TENSOR_ORIENTATION','geometry_classification':'GEOMETRY_APPROXIMATES_LEARNED','corrected_numerical_classification':'C3_NUMERICALLY_DOMINATED','direct_apply_classification':'C3_DIRECT_APPLY_FEASIBILITY_CONFIRMED','canonical_runtime_comparison':'PARTIALLY_VALID','combined_direction':'STOP_C3','recommendation':'STOP_C3','root_cause':'Parallel hard-gate reshaped flat GGML data as (5120,1024) and transposed it. Correct W[out,in] is flat.reshape(1024,5120). Canonical bytes/dequantization and metric aggregation are identical. The wrong reshape alone reproduces the ~2x canonical errors on the same eight activations.','numerical_rate_quality':'Independent Stage-2 canonical values are confirmed. IQ2_XS at 2.3125 bpw / 0.1148 dominates C3 at 3.0001 bpw / 0.2016. Runtime is excluded.','runtime_interpretation':'Packed 3-bit direct W*x feasibility is accepted. The finished fairness audit invalidates the original C3 speed advantage and finds native canonical kernels faster, but its report and raw/structured latency magnitudes disagree; comparative direction is usable while exact ratios are not.','c4_tail':'Preserved unchanged: 4.0481 bpw, real W*x 0.0556, numerical Pareto in Stage-2, direct apply unproven.'}
 write_csv(out/'provenance.csv',provenance);write_csv(out/'evidence-comparison.csv',comparison);write_csv(out/'methodology-comparison.csv',method);write_csv(out/'common-vector-results.csv',common);write_csv(out/'canonical-byte-equivalence.csv',byte_rows);write_csv(out/'tensor-equivalence.csv',tensor_rows)
 premerge=f'''Stage-2 branch: vbuf-ml\nStage-2 HEAD: {STAGE2_COMMIT}\nParallel branch: vBuf_3\nParallel research commit: {PARALLEL_COMMIT}\nMerge base: {MERGE_BASE}\nStage-2 independent commits: b9043fb, b9316d9\nParallel independent commits: 889bd58\nMerge commit: {MERGE_COMMIT}\n''';(raw/'pre-merge-provenance.txt').write_text(premerge)
 evidence={'summary':summary,'source':{'model_sha256':modelhash,'tensor':TARGET,'byte_range':[t.absolute_start,t.absolute_end],'ggml_dimensions':list(t.shape),'logical_input':5120,'logical_output':1024,'q8_fp32_sha256':q8hash},'method_sources':{'parallel_hard_gate_script':str(a.parallel_root/'scripts/qualify_ccc_hard_gate.py'),'parallel_hard_gate_script_sha256':sha_file(a.parallel_root/'scripts/qualify_ccc_hard_gate.py'),'parallel_canonical_bridge_sha256':sha_file(a.parallel_root/'c/canonical_bridge.cpp'),'independent_stage2_script_sha256':sha_file(ROOT/'scripts/qualify_ccc_stage2.py'),'equivalence_helper_sha256':sha_file(ROOT/'integrations/llama.cpp/step32_canonical_equivalence.cpp')},'common_vectors':{'count':8,'sha256':xhash,'selection':'independent Stage-2 functional-test vectors 0..7'},'canonical_bytes':byte_rows,'tensor_equivalence':tensor_rows,'git_provenance':{'stage2_commit':STAGE2_COMMIT,'parallel_research_commit':PARALLEL_COMMIT,'merge_base':MERGE_BASE,'merge_commit':MERGE_COMMIT,'merge_first_parent':STAGE2_COMMIT,'merge_second_parent':PARALLEL_COMMIT,'historically_independent':True},'iq_provenance':iq_prov,'runtime_audit':{'historical_comparison':'INVALID','finished_audit_direction':'canonical kernels faster than AVX2 C3','classification':'PARTIALLY_VALID','reason':'raw/JSON/CSV agree on canonical-faster direction and one latency set; fairness-audit-report.md contains a different latency set while reaching the same direction'},'reported_results':{'parallel':{k:pr[k]['real_wx_mean_rel_l2'] for k in ('C3-A Learned (Lloyd-Max)','Canonical Q2_K','Canonical Q3_K','Canonical Q4_K')},'stage2':{k:sr[k]['real_mean_relative_l2'] for k in ('CCC C3 learned','Q2_K','Q3_K','Q4_K')}}};(out/'reconciliation.json').write_text(json.dumps(evidence,indent=2)+'\n');report(out,evidence,common);log.append(json.dumps({'status':'PASS',**summary}));(raw/'runner.log').write_text('\n'.join(log)+'\n');print(log[-1])
def report(out,e,common):
 s=e['summary'];rows={(r['pipeline'],r['candidate']):r for r in common};g=e['git_provenance'];lines=['# CCC evidence reconciliation','','## Git provenance','',f"- Stage-2 commit: `{g['stage2_commit']}`",f"- Parallel research commit: `{g['parallel_research_commit']}`",f"- Merge base: `{g['merge_base']}`",f"- No-ff merge commit: `{g['merge_commit']}`",'- The merge has Stage-2 as first parent and the independently preserved parallel branch as second parent. No rebase or squash was used.','', '## Agreements','','- Learned C3 remains near 0.20–0.21 real W*x error in both independent branches.','- Bounded power geometry remains close to learned C3.','- Packed 3-bit direct W*x without dense reconstruction is feasible.','','## Disagreements','','- Parallel canonical errors were about 2x larger. This is resolved below as a tensor-orientation bug.','- The original parallel native benchmark claimed C3 was faster; its later fairness audit invalidates that claim.','','## Result','',f"**Root cause:** `{s['root_cause_classification']}`",'',s['root_cause'],'','The parallel branch used:','```python','W_mat = flat.reshape(5120, 1024)','W_eval = W_mat.T','y = X @ W_eval.T','```','The correct GGML-to-NumPy mapping is:','```python','W = flat.reshape(1024, 5120)  # W[out, in]','y = X @ W.T','```','','Both produce an apparent `[1024,5120]` matrix, but only the second preserves contiguous 5120-weight GGML rows.','','For both branches the intended metric is:','```python','y_ref       = X @ W_ref.T','y_candidate = X @ W_candidate.T','error_i     = y_candidate[i] - y_ref[i]','rel_l2_i    = norm(error_i, 2) / norm(y_ref[i], 2)','reported    = mean(rel_l2_i for i in vectors)','```','The parallel bug changes both `W_ref` and `W_candidate` before these otherwise identical formulas.','','## Common eight-vector localization','','Candidate | parallel as written | Stage-2 | parallel corrected','---|---:|---:|---:']
 for c in ('CCC C3 learned','Q2_K','Q3_K','Q4_K'):lines.append(f"{c} | {rows[('parallel_as_written',c)]['mean_per_vector_relative_l2']:.6f} | {rows[('independent_stage2',c)]['mean_per_vector_relative_l2']:.6f} | {rows[('parallel_corrected',c)]['mean_per_vector_relative_l2']:.6f}")
 lines+=['','Correcting only the reshape makes the parallel pipeline bit/formula equivalent to Stage-2. Prompt population and split are therefore not the cause.','','## Equivalence chain','','- Same model and tensor byte range.','- Same flat Q8 FP32 hash.','- Q2_K/Q3_K/Q4_K serialized bytes are byte-identical across `ggml_quantize_chunk` and the parallel direct entry points.','- Canonical dequantized FP32 tensors are bit-identical.','- Both branches average per-vector relative L2.','- The discrepancy appears only when flat tensors are mapped to matrix coordinates.','','## Orientation invariant','','- GGML metadata: `ne[0]=5120`, `ne[1]=1024`.','- Logical input: 5120.','- Logical output: 1024.','- Flat storage: 1024 contiguous rows, each containing 5120 input weights.','- NumPy: `W.shape == (1024,5120)`.','- Apply: `X.shape == (n,5120)` and `Y = X @ W.T`.','','## Hidden-state seam','','Both captures are semantically pre-key-projection inputs. The parallel callback identifies the F32 operand paired with `blk.32.attn_k.weight`; Stage-2 names `attn_norm-32` and additionally validates against `Kcur-32` at correlation 0.999990843. The common-vector test uses the known-good Stage-2 seam and removes capture variation.','','## IQ controls','','Only IQ2_XXS and IQ2_XS in Stage-2 are activation-aware. Their imatrix is mean-square feature importance from the 64 functional-validation vectors. Functional test vectors remain untouched. IQ2_S, IQ3_XXS, IQ3_S, IQ4_NL, and IQ4_XS use no imatrix in the pinned API and must not be labeled activation-aware.','','## Combined classifications','',f"Geometry: `{s['geometry_classification']}`",f"Numerical rate/quality: `{s['corrected_numerical_classification']}`",f"Direct compute: `{s['direct_apply_classification']}`",f"Canonical runtime comparison: `{s['canonical_runtime_comparison']}`",f"Combined direction: `{s['combined_direction']}`",'','## Corrected numerical interpretation','',f"`{s['corrected_numerical_classification']}`",'',s['numerical_rate_quality'],'','C4+0.1% tail remains visible and unchanged: 4.0481 bpw, 0.0556 real W*x, Stage-2 numerical Pareto, direct apply unproven.','','## Runtime interpretation','',f"`{s['direct_apply_classification']}`",'',f"Canonical comparison: `{s['canonical_runtime_comparison']}`",'',s['runtime_interpretation'],'','Numerical rate/quality Pareto and future rate/quality/runtime Pareto are separate claims.','','## Recommendation','',f"`{s['recommendation']}`",'','The bounded recommendation is to stop C3 promotion: corrected rate/quality is dominated and the finished CPU fairness audit removes the claimed runtime advantage. Preserve direct-apply feasibility as a technical result. Do not execute more implementation or broad search in this reconciliation step.','','## Stop','','No vBuf, vBuf-ML, representation, native-kernel, C4-tail, cross-layer, or production-runtime changes were made.'];(out/'reconciliation-report.md').write_text('\n'.join(lines)+'\n')
if __name__=='__main__':main()
