#!/usr/bin/env python3
"""Post-merge reconciliation of independently preserved vBuf_4 CCC evidence."""
from __future__ import annotations
import csv,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
STAGE1='b9043fb';STAGE2='b9316d9b83f4d193aec10d4b5cbead53d0963e79';VBUF3='889bd58c674195b9e40f0156e56ca18c1fd00e78';VBUF4='28588a048a02ee3f4df33530dff8ee789e290114';BASE='33a4d037015b09394b762d5df159dad6d42f8643';PREVIOUS='1ea629b8fabf882065472604065e68dee5e51ea0';MERGE='53afb10b26af6a57a8a4ff6bf7c80728c850f39e'
def readcsv(p):
 with p.open() as f:return list(csv.DictReader(f))
def writecsv(p,rows):
 fields=[]
 for r in rows:
  for k in r:
   if k not in fields:fields.append(k)
 with p.open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=fields,lineterminator='\n');w.writeheader();w.writerows(rows)
def main():
 import argparse
 ap=argparse.ArgumentParser();ap.add_argument('--output-dir',type=Path,default=ROOT/'benchmark-results/vbuf-ml-step33-ccc-structured-reconciliation');a=ap.parse_args();out=a.output_dir;raw=out/'raw';raw.mkdir(parents=True,exist_ok=True)
 imported=ROOT/'benchmark-results/ccc-structured-baseline-qualification';summary=json.loads((imported/'summary.json').read_text());pred=readcsv(imported/'predictor-quality.csv');matrix=readcsv(imported/'ccc_structured_baseline_qualification.csv');stage1=readcsv(ROOT/'benchmark-results/vbuf-ml-step30-ccc-assessment/representation-assessment.csv')
 provenance=[
 {'evidence':'Stage-1 49-tensor CCC assessment','source_branch':'vbuf-ml','source_commit':'b9043fb','artifact_path':'benchmark-results/vbuf-ml-step30-ccc-assessment/','created_before_vbuf4_merge':True,'status':'historical'},
 {'evidence':'Stage-2 canonical and hidden-state qualification','source_branch':'vbuf-ml','source_commit':STAGE2,'artifact_path':'benchmark-results/vbuf-ml-step31-ccc-canonical/','created_before_vbuf4_merge':True,'status':'historical'},
 {'evidence':'parallel C3/native qualification','source_branch':'vBuf_3','source_commit':VBUF3,'artifact_path':'benchmark-results/vbuf-ml-step31-ccc-hard-gate/; benchmark-results/ccc-c3-native-*','created_before_vbuf4_merge':True,'status':'merged independently'},
 {'evidence':'structured CCC baseline qualification','source_branch':'vBuf_4','source_commit':VBUF4,'artifact_path':'benchmark-results/ccc-structured-baseline-qualification/','created_before_vbuf4_merge':True,'status':'imported unchanged'},
 {'evidence':'structured concept audit','source_branch':'vBuf_4','source_commit':VBUF4,'artifact_path':'docs/vbuf-ml/ccc_concept_audit.md','created_before_vbuf4_merge':True,'status':'imported unchanged'},
 {'evidence':'vBuf_4 no-ff merge','source_branch':'vbuf-ml','source_commit':MERGE,'artifact_path':'Git merge commit','created_before_vbuf4_merge':False,'status':'first parent '+PREVIOUS+'; second parent '+VBUF4},
 {'evidence':'structured-branch reconciliation','source_branch':'vbuf-ml','source_commit':'commit containing this artifact','artifact_path':'benchmark-results/vbuf-ml-step33-ccc-structured-reconciliation/','created_before_vbuf4_merge':False,'status':'post-merge reconciliation'}]
 methodology=[
 {'property':'model','vBuf_4':'Qwen3-32B-Q8_0.gguf / 2c50eb8a…','existing_evidence':'same verified Q8_0 source','same':'YES','interpretation':'Q8-relative; no BF16 claim'},
 {'property':'tensor','vBuf_4':'blk.0.attn_k.weight','existing_evidence':'Stage-1 includes same tensor; Stage-2 uses blk.32.attn_k.weight','same':'PARTIAL','interpretation':'Direct anchor comparison is with Stage-1 blk.0; Stage-2 is cross-layer corroboration only.'},
 {'property':'orientation','vBuf_4':'GGML [5120,1024] -> reshape(1024,5120)','existing_evidence':'correct W[out,in] invariant','same':'YES','interpretation':'No vBuf_3 reshape bug.'},
 {'property':'representation split','vBuf_4':'splitmix64 50/25/25 over all coordinates','existing_evidence':'Stage-1 position hash 70/15/15 sampled; Stage-2 70/15/15','same':'NO','interpretation':'Independent methodology; conclusions compared, not averaged.'},
 {'property':'canonical quantizer','vBuf_4':'pinned llama-quantize on minimal F32 GGUF','existing_evidence':'Stage-2 ggml_quantize_chunk on Q8 reconstruction','same':'PINNED DIFFERENT ENTRY','interpretation':'Same pinned llama.cpp; different tensors prevent byte comparison.'},
 {'property':'canonical dequantizer','vBuf_4':'NumPy ports checked against pinned C to 5e-10','existing_evidence':'pinned type-trait to_float','same':'NUMERICALLY EQUIVALENT CLAIM','interpretation':'No discrepancy observed, but not a shared-byte test.'},
 {'property':'functional inputs','vBuf_4':'3 deterministic Gaussian probes','existing_evidence':'Stage-2 64 real hidden-state test vectors','same':'NO','interpretation':'vBuf_4 functional evidence is secondary and not relabeled real.'},
 {'property':'direct apply','vBuf_4':'structured algebra verified 1.4e-15; no kernel','existing_evidence':'packed plain C3 direct apply confirmed on vBuf_3','same':'DIFFERENT REPRESENTATION','interpretation':'No structured-baseline kernel qualification.'}]
 # Direct comparison with Stage-1 anchors on the same blk.0 tensor.
 comparison=[]
 for p in pred:
  if p['baseline'] in ('raw','B0','B1','B2','B3','B4','B5'):comparison.append({'evidence':'vBuf_4 predictor residual','source_commit':VBUF4,'tensor':'blk.0.attn_k.weight','candidate':p['baseline'],'true_bpw':p['metadata_bpw'],'rmse':p['residual_rms'],'relative_l2_or_rms_ratio':p['residual_rms_over_raw_rms'],'p99_9':p['residual_p99_9'],'max_error':p['residual_max'],'functional_wx':'not evaluated for predictor alone','interpretation':'structured baseline contribution'})
 for r in stage1:
  if r['tensor_name']=='blk.0.attn_k.weight' and r['family']=='CCC additive' and r['nominal_bits']=='3' and r['position_context']=='none' and r['ccc_anchor'] in ('zero','tensor_mean','row_mean','column_mean','row+column'):
   comparison.append({'evidence':'Stage-1 same-tensor anchor','source_commit':'b9043fb','tensor':r['tensor_name'],'candidate':r['ccc_anchor'],'true_bpw':r['true_bits_per_weight'],'rmse':r['rmse'],'relative_l2_or_rms_ratio':r['relative_l2'],'p99_9':r['p999_error'],'max_error':r['max_absolute_error'],'functional_wx':'not tested','interpretation':'independent sampled anchor assessment'})
 for name in ('B0_G0_free8','B0_G2_power_g1.25','B0_G3_tail_g1.25','B0_G4_nozero','B5_G3_tail_g1.25','canonical_Q2_K','canonical_Q3_K','canonical_Q4_0'):
  hits=[r for r in matrix if r['candidate']==name]
  if hits:
   r=hits[0];comparison.append({'evidence':'vBuf_4 candidate matrix','source_commit':VBUF4,'tensor':'blk.0.attn_k.weight','candidate':name,'true_bpw':r['true_bpw'],'rmse':r['weight_rmse'],'relative_l2_or_rms_ratio':r['rel_l2'],'p99_9':r['p99_9'],'max_error':r['max'],'functional_wx':r['wx_rel_l2_mean'] or 'not tested','interpretation':'Q8-relative, TEST split'})
 classifications={'structured_baseline':'STRUCTURED_BASELINE_REJECTED','geometry':'GEOMETRY_APPROXIMATES_LEARNED','c3_numerical_rate_quality':'C3_NUMERICALLY_DOMINATED','c3_direct_apply':'C3_DIRECT_APPLY_FEASIBILITY_CONFIRMED','combined_direction':'STOP_C3'}
 agreements=['vBuf_4 and Stage-1 independently find zero/tensor anchors tied and row/column anchors non-beneficial on blk.0.attn_k.weight.','vBuf_4 and Stage-2 both place plain learned/geometric C3 near approximately 0.20 action/relative error.','No evidence supports contextual prediction as the source of low-bit accuracy.','No production representation is justified.']
 distinctions=['vBuf_4 evaluates blk.0, while Stage-2 real hidden states evaluate blk.32.','vBuf_4 uses Gaussian probes only; it does not supersede real-hidden-state evidence.','vBuf_4 G2/G3 include an exact zero state; its G4 no-zero control is the closer analogue to Stage-2/parallel mid-riser C3.','vBuf_4 predates IQ controls; Stage-2 IQ2_XS remains decisive for numerical domination.']
 result={'git_provenance':{'pre_merge_head':PREVIOUS,'vbuf4_original_head':BASE,'vbuf4_preservation_commit':VBUF4,'merge_base':BASE,'merge_commit':MERGE,'merge_first_parent':PREVIOUS,'merge_second_parent':VBUF4,'historically_independent':True},'source_summary':summary,'classifications':classifications,'agreements':agreements,'distinctions':distinctions,'c4_tail_preserved':'Stage-2 C4+0.1% tail remains 4.0481 bpw / 0.0556 real W*x / direct apply unproven','production_changes':0}
 writecsv(out/'provenance.csv',provenance);writecsv(out/'methodology-comparison.csv',methodology);writecsv(out/'evidence-comparison.csv',comparison);(out/'reconciliation.json').write_text(json.dumps(result,indent=2)+'\n');(raw/'pre-merge-provenance.txt').write_text(f'current pre-merge HEAD: {PREVIOUS}\nvBuf_4 branch: vBuf_4\nvBuf_4 original HEAD: {BASE}\nvBuf_4 preservation: {VBUF4}\nmerge base: {BASE}\nmerge commit: {MERGE}\n');(raw/'runner.log').write_text(json.dumps({'status':'PASS','classifications':classifications})+'\n');report(out,result,comparison);print(json.dumps({'status':'PASS','classifications':classifications}))
def report(out,r,rows):
 g=r['git_provenance'];c=r['classifications'];lines=['# vBuf_4 structured CCC evidence reconciliation','','## Git provenance','',f"- Pre-merge current HEAD: `{g['pre_merge_head']}`",f"- vBuf_4 original HEAD / merge base: `{g['vbuf4_original_head']}`",f"- vBuf_4 preservation commit: `{g['vbuf4_preservation_commit']}`",f"- No-ff merge: `{g['merge_commit']}`",'- Histories were preserved as separate parents; no squash or rebase.','','## Imported evidence','','The imported branch evaluated 111 structured-baseline/residual-alphabet candidates on `blk.0.attn_k.weight` from the same verified Q8_0 model. It used the correct `(1024,5120)` NumPy orientation. Imported artifacts remain unchanged.','','## Agreements']
 lines += ['']+['- '+x for x in r['agreements']]+['','## Scope distinctions','']+['- '+x for x in r['distinctions']]
 lines += ['','## Structured predictor result','','On the untouched vBuf_4 TEST split, B1–B5 change residual RMS by at most about 0.12%; row, column, and row+column predictors do not reduce residual energy. Stage-1 independently shows the same pattern on this exact tensor: zero/tensor anchors tie, while row/column metadata slightly worsens C3 error.','','## Alphabet result','','vBuf_4 zero-state power families G2/G3 trail free Lloyd-Max by approximately 5.7–13%. Its no-zero G4 is better than those controls and is the proper analogue of the mid-riser C3 tested elsewhere. This supports a nonuniform scalar alphabet, not contextual correction. Stage-2 IQ controls still dominate C3 under rate × quality.','','## Canonical and functional limits','','vBuf_4 uses pinned canonical controls and three Gaussian W*x probes. It has no real hidden-state evidence and therefore does not supersede Stage-2. Its best CCC-family W*x point is about 0.2125 versus Q3_K about 0.1545 on its probes.','','## Combined classifications','',f"Structured baseline: `{c['structured_baseline']}`",f"Geometry: `{c['geometry']}`",f"C3 numerical rate/quality: `{c['c3_numerical_rate_quality']}`",f"C3 direct apply: `{c['c3_direct_apply']}`",f"Combined direction: `{c['combined_direction']}`",'','C4+0.1% tail remains unchanged and visible: 4.0481 bpw, 0.0556 real W*x, direct apply unproven.','','## Recommendation','','`STOP_C3`','','The independent vBuf_4 evidence strengthens rejection of the contextual/structured-baseline premise on attention key projections. Preserve it as bounded single-tensor evidence; do not broaden, implement, or modify production architecture.','','## Stop','','No vBuf, vBuf-ML, quantizer, native-kernel, or production-runtime changes were made.'];(out/'reconciliation-report.md').write_text('\n'.join(lines)+'\n')
if __name__=='__main__':main()
